# Generated by Django 4.0.2 on 2022-03-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
