# Generated by Django 4.0.2 on 2022-03-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
