# Generated by Django 4.0.2 on 2022-03-13 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_book_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book',
            new_name='title',
        ),
    ]
