# Generated by Django 4.0.2 on 2022-03-13 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
